CREATE TABLE [Polaris].[CircItemRecords] (
    [ItemRecordID] int IDENTITY,
    [Barcode] nvarchar(20),
    [ItemStatusID] int,
    [LastCircTransactionDate] datetime,
    [AssociatedBibRecordID] int,
    [ParentItemRecordID] int,
    [RecordStatusID] int,
    [AssignedBranchID] int,
    [AssignedCollectionID] int,
    [MaterialTypeID] int,
    [LastUsePatronID] int,
    [LastUseBranchID] int,
    [YTDCircCount] int DEFAULT (0),
    [LifetimeCircCount] int DEFAULT (0),
    [YTDInHouseUseCount] int DEFAULT (0),
    [LifetimeInHouseUseCount] int DEFAULT (0),
    [FreeTextBlock] nvarchar(255),
    [ManualBlockID] int,
    [FineCodeID] int,
    [LoanPeriodCodeID] int,
    [StatisticalCodeID] int,
    [ShelfLocationID] int,
    [ILLFlag] bit DEFAULT (0),
    [DisplayInPAC] bit DEFAULT ((1)),
    [RenewalLimit] int,
    [Holdable] bit DEFAULT ((1)),
    [HoldableByPickup] bit DEFAULT ((0)),
    [HoldableByBranch] bit DEFAULT ((0)),
    [HoldableByLibrary] bit DEFAULT ((0)),
    [LoanableOutsideSystem] bit DEFAULT ((0)),
    [NonCirculating] bit DEFAULT ((0)),
    [RecordStatusDate] datetime DEFAULT (getdate()),
    [LastCircWorkstationID] int,
    [LastCircPolarisUserID] int,
    [HoldableByPrimaryLender] bit DEFAULT ((0)),
    [OriginalCheckOutDate] datetime,
    [OriginalDueDate] datetime,
    [ItemStatusDate] datetime,
    [CheckInBranchID] int,
    [CheckInDate] datetime,
    [InTransitSentBranchID] int,
    [InTransitSentDate] datetime,
    [InTransitRecvdBranchID] int,
    [InTransitRecvdDate] datetime,
    [CheckInWorkstationID] int,
    [CheckInUserID] int,
    [LastCheckOutRenewDate] datetime,
    [ShelvingBit] bit DEFAULT ((0)),
    [FirstAvailableDate] datetime,
    [LoaningOrgID] int,
    [HomeBranchID] int,
    [ItemDoesNotFloat] bit DEFAULT ((0)),
    [EffectiveDisplayInPAC] bit DEFAULT ((0)),
    [DoNotMailToPatron] bit DEFAULT ((0)),
    [ElectronicItem] bit DEFAULT ((0)),
    [LastDueDate] datetime,
    [ResourceEntityID] int,
    [HoldPickupBranchID] int,
    [EffectiveItemStatusID] int,
    [DelayedHoldsFlag] bit DEFAULT ((0)),
    [DelayedNumberOfDays] int,
    [LanguageID] smallint,
    [DisplayInPACLastChanged] datetime DEFAULT (getdate()),
    CONSTRAINT [fk_ItemShelfLocation] FOREIGN KEY ([ShelfLocationID],[AssignedBranchID]) REFERENCES [Polaris].[ShelfLocations]([ShelfLocationID],[OrganizationID]),
    CONSTRAINT [fk_CircItemRecords_CheckInWorkstationID] FOREIGN KEY ([CheckInWorkstationID]) REFERENCES [Polaris].[Workstations]([WorkstationID]),
    CONSTRAINT [fk_CircItemRecords_InTransitSentBranchID] FOREIGN KEY ([InTransitSentBranchID]) REFERENCES [Polaris].[Organizations]([OrganizationID]),
    CONSTRAINT [fk_ItemBib] FOREIGN KEY ([AssociatedBibRecordID]) REFERENCES [Polaris].[BibliographicRecords]([BibliographicRecordID]),
    CONSTRAINT [fk_ItemBlockRecord] FOREIGN KEY ([ManualBlockID]) REFERENCES [Polaris].[ItemBlockDescriptions]([ItemBlockID]),
    CONSTRAINT [fk_CircItemRecords_Workstations] FOREIGN KEY ([LastCircWorkstationID]) REFERENCES [Polaris].[Workstations]([WorkstationID]),
    CONSTRAINT [fk_CircItemRecords_ResourceEntityID] FOREIGN KEY ([ResourceEntityID]) REFERENCES [Polaris].[ResourceEntities]([ResourceEntityID]),
    CONSTRAINT [fk_ItemStatisticalCode] FOREIGN KEY ([StatisticalCodeID],[AssignedBranchID]) REFERENCES [Polaris].[StatisticalCodes]([StatisticalCodeID],[OrganizationID]),
    CONSTRAINT [fk_StatusCodeItem] FOREIGN KEY ([RecordStatusID]) REFERENCES [Polaris].[RecordStatuses]([RecordStatusID]),
    CONSTRAINT [FK_FineCodeID_CircItemRecords] FOREIGN KEY ([FineCodeID]) REFERENCES [Polaris].[FineCodes]([FineCodeID]),
    CONSTRAINT [FK_LoanPeriodCodeID_CircItemRecords] FOREIGN KEY ([LoanPeriodCodeID]) REFERENCES [Polaris].[LoanPeriodCodes]([LoanPeriodCodeID]),
    CONSTRAINT [fk_ItemParentChild] FOREIGN KEY ([ParentItemRecordID]) REFERENCES [Polaris].[CircItemRecords]([ItemRecordID]),
    CONSTRAINT [FK_CircItemRecords_OrganizationsCollections] FOREIGN KEY ([AssignedCollectionID],[AssignedBranchID]) REFERENCES [Polaris].[OrganizationsCollections]([CollectionID],[OrganizationID]),
    CONSTRAINT [fk_HoldPickupBranchID_CircItemRecords] FOREIGN KEY ([HoldPickupBranchID]) REFERENCES [Polaris].[Organizations]([OrganizationID]),
    CONSTRAINT [fk_AssignedBranchItem] FOREIGN KEY ([AssignedBranchID]) REFERENCES [Polaris].[Organizations]([OrganizationID]),
    CONSTRAINT [fk_LastUseBranch] FOREIGN KEY ([LastUseBranchID]) REFERENCES [Polaris].[Organizations]([OrganizationID]),
    CONSTRAINT [FK_CircItemRecords_LanguageID] FOREIGN KEY ([LanguageID]) REFERENCES [Polaris].[Languages]([LanguageID]),
    CONSTRAINT [fk_CircItemRecords_CheckInUserID] FOREIGN KEY ([CheckInUserID]) REFERENCES [Polaris].[PolarisUsers]([PolarisUserID]),
    CONSTRAINT [fk_CircItemRecords_LastUsePatron] FOREIGN KEY ([LastUsePatronID]) REFERENCES [Polaris].[Patrons]([PatronID]),
    CONSTRAINT [fk_CircItemRecords_InTransitRecvdBranchID] FOREIGN KEY ([InTransitRecvdBranchID]) REFERENCES [Polaris].[Organizations]([OrganizationID]),
    CONSTRAINT [fk_CircStatusItem] FOREIGN KEY ([ItemStatusID]) REFERENCES [Polaris].[ItemStatuses]([ItemStatusID]),
    CONSTRAINT [fk_ItemMatType] FOREIGN KEY ([MaterialTypeID]) REFERENCES [Polaris].[MaterialTypes]([MaterialTypeID]),
    CONSTRAINT [fk_CircItemRecords_LoaningOrgID] FOREIGN KEY ([LoaningOrgID]) REFERENCES [Polaris].[Organizations]([OrganizationID]),
    CONSTRAINT [FK_HomeBranchID_CircItemRecords] FOREIGN KEY ([HomeBranchID]) REFERENCES [Polaris].[Organizations]([OrganizationID]),
    CONSTRAINT [fk_CircItemRecords_CheckInBranchID] FOREIGN KEY ([CheckInBranchID]) REFERENCES [Polaris].[Organizations]([OrganizationID]),
    CONSTRAINT [fk_CircItemRecords_PolarisUsers] FOREIGN KEY ([LastCircPolarisUserID]) REFERENCES [Polaris].[PolarisUsers]([PolarisUserID]),
    PRIMARY KEY ([ItemRecordID])
);