CREATE TABLE [Polaris].[Patrons] (
    [PatronID] int IDENTITY,
    [PatronCodeID] int,
    [OrganizationID] int,
    [CreatorID] int,
    [ModifierID] int,
    [Barcode] nvarchar(20),
    [SystemBlocks] int DEFAULT ((0)),
    [YTDCircCount] int DEFAULT ((0)),
    [LifetimeCircCount] int DEFAULT ((0)),
    [LastActivityDate] datetime,
    [ClaimCount] int DEFAULT ((0)),
    [LostItemCount] int DEFAULT (0),
    [ChargesAmount] money DEFAULT (0),
    [CreditsAmount] money DEFAULT (0),
    [RecordStatusID] int DEFAULT ((1)),
    [RecordStatusDate] datetime DEFAULT (getdate()),
    [YTDYouSavedAmount] money DEFAULT ((0)),
    [LifetimeYouSavedAmount] money DEFAULT ((0)),
    CONSTRAINT [fk_Patrons_RecordStatuses] FOREIGN KEY ([RecordStatusID]) REFERENCES [Polaris].[RecordStatuses]([RecordStatusID]),
    CONSTRAINT [fk_PatronBranch] FOREIGN KEY ([OrganizationID]) REFERENCES [Polaris].[Organizations]([OrganizationID]),
    CONSTRAINT [fk_PatronRecCreatedBy] FOREIGN KEY ([CreatorID]) REFERENCES [Polaris].[PolarisUsers]([PolarisUserID]),
    CONSTRAINT [fk_PatronRecModifiedBy] FOREIGN KEY ([ModifierID]) REFERENCES [Polaris].[PolarisUsers]([PolarisUserID]),
    CONSTRAINT [fk_PatronCodesRecord] FOREIGN KEY ([PatronCodeID]) REFERENCES [Polaris].[PatronCodes]([PatronCodeID]),
    PRIMARY KEY ([PatronID])
);