CREATE TABLE [Polaris].[NotificationLog] (
    [PatronID] int,
    [NotificationDateTime] datetime,
    [NotificationTypeID] int,
    [DeliveryOptionID] int,
    [DeliveryString] nvarchar(255),
    [OverduesCount] int,
    [HoldsCount] int,
    [CancelsCount] int,
    [RecallsCount] int,
    [NotificationStatusID] int,
    [Details] nvarchar(255),
    [RoutingsCount] int DEFAULT (0),
    [ReportingOrgID] int,
    [PatronBarcode] nvarchar(20),
    [Reported] bit DEFAULT ((0)),
    [Overdues2ndCount] int,
    [Overdues3rdCount] int,
    [BillsCount] int,
    [LanguageID] int,
    [CarrierName] nvarchar(255),
    [ManualBillCount] int,
    [NotificationLogID] int IDENTITY,
    PRIMARY KEY ([NotificationLogID])
);