CREATE TABLE [Polaris].[PatronRegistration] (
    [PatronID] int,
    [LanguageID] smallint,
    [NameFirst] nvarchar(32),
    [NameLast] nvarchar(100),
    [NameMiddle] nvarchar(32),
    [NameTitle] nvarchar(8),
    [NameSuffix] nvarchar(4),
    [PhoneVoice1] nvarchar(20),
    [PhoneVoice2] nvarchar(20),
    [PhoneVoice3] nvarchar(20),
    [EmailAddress] nvarchar(64),
    [EntryDate] datetime,
    [ExpirationDate] datetime,
    [AddrCheckDate] datetime,
    [UpdateDate] datetime,
    [User1] nvarchar(64),
    [User2] nvarchar(64),
    [User3] nvarchar(64),
    [User4] nvarchar(64),
    [User5] nvarchar(64),
    [Birthdate] datetime,
    [RegistrationDate] datetime,
    [FormerID] nvarchar(20),
    [ReadingList] tinyint DEFAULT (0),
    [PhoneFAX] nvarchar(20),
    [DeliveryOptionID] int,
    [StatisticalClassID] int DEFAULT (null),
    [CollectionExempt] bit DEFAULT (0),
    [AltEmailAddress] nvarchar(64),
    [ExcludeFromOverdues] bit DEFAULT (0),
    [SDIEmailAddress] nvarchar(150),
    [SDIEmailFormatID] int,
    [SDIPositiveAssent] bit,
    [SDIPositiveAssentDate] datetime,
    [DeletionExempt] bit DEFAULT (0),
    [PatronFullName] nvarchar(100),
    [ExcludeFromHolds] bit DEFAULT (0),
    [ExcludeFromBills] bit DEFAULT (0),
    [EmailFormatID] int DEFAULT (2),
    [PatronFirstLastName] nvarchar(100),
    [Username] nvarchar(50),
    [MergeDate] datetime,
    [MergeUserID] int,
    [MergeBarcode] nvarchar(20),
    [EnableSMS] bit,
    [RequestPickupBranchID] int,
    [Phone1CarrierID] int,
    [Phone2CarrierID] int,
    [Phone3CarrierID] int,
    [eReceiptOptionID] int,
    [TxtPhoneNumber] tinyint,
    [ExcludeFromAlmostOverdueAutoRenew] bit DEFAULT ((0)),
    [ExcludeFromPatronRecExpiration] bit DEFAULT ((0)),
    [ExcludeFromInactivePatron] bit DEFAULT ((0)),
    [DoNotShowEReceiptPrompt] bit DEFAULT ((0)),
    [PasswordHash] nvarchar(256),
    [ObfuscatedPassword] nvarchar(256),
    [NameTitleID] int,
    [RBdigitalPatronID] int,
    [GenderID] int,
    [LegalNameFirst] nvarchar(32),
    [LegalNameLast] nvarchar(32),
    [LegalNameMiddle] nvarchar(32),
    [LegalFullName] nvarchar(100),
    [UseLegalNameOnNotices] bit DEFAULT ((0)),
    [EnablePush] bit DEFAULT ((0)),
    [StaffAcceptedUseSingleName] bit DEFAULT ((0)),
    [ExtendedLoanPeriods] bit DEFAULT ((0)),
    [IncreasedCheckOutLimits] bit DEFAULT ((0)),
    CONSTRAINT [fk_Genders] FOREIGN KEY ([GenderID]) REFERENCES [Polaris].[Genders]([GenderID]),
    CONSTRAINT [fk_PatRegDeliveryOptions] FOREIGN KEY ([DeliveryOptionID]) REFERENCES [Polaris].[SA_DeliveryOptions]([DeliveryOptionID]),
    CONSTRAINT [fk_PatronRegistraion_PatronStatClassCodes] FOREIGN KEY ([StatisticalClassID]) REFERENCES [Polaris].[PatronStatClassCodes]([StatisticalClassID]),
    CONSTRAINT [fk_LanguagePat] FOREIGN KEY ([LanguageID]) REFERENCES [Polaris].[Languages]([LanguageID]),
    CONSTRAINT [fk_NameTitles] FOREIGN KEY ([NameTitleID]) REFERENCES [Polaris].[NameTitles]([NameTitleID]),
    CONSTRAINT [fk_PatronRegistration_RequestPickupBranchID] FOREIGN KEY ([RequestPickupBranchID]) REFERENCES [Polaris].[Organizations]([OrganizationID]),
    CONSTRAINT [FK_MergeUserID_PatronRegistration] FOREIGN KEY ([MergeUserID]) REFERENCES [Polaris].[PolarisUsers]([PolarisUserID]),
    CONSTRAINT [fk_PatronRegistration_EmailFormatID] FOREIGN KEY ([EmailFormatID]) REFERENCES [Polaris].[EmailFormat]([EmailFormatID]),
    CONSTRAINT [fk_PatronRelationship] FOREIGN KEY ([PatronID]) REFERENCES [Polaris].[Patrons]([PatronID]),
    PRIMARY KEY ([PatronID])
);