CREATE TABLE [Polaris].[BibliographicRecords] (
    [BibliographicRecordID] int IDENTITY,
    [RecordStatusID] int DEFAULT ((1)),
    [RecordOwnerID] int,
    [CreatorID] int DEFAULT ((1)),
    [ModifierID] int,
    [BrowseAuthor] nvarchar(255),
    [BrowseTitle] nvarchar(255),
    [BrowseCallNo] nvarchar(255),
    [DisplayInPAC] tinyint DEFAULT (1),
    [ImportedDate] datetime,
    [MARCBibStatus] char(1) DEFAULT ('n'),
    [MARCBibType] char(1) DEFAULT (' '),
    [MARCBibLevel] char(1) DEFAULT ('c'),
    [MARCTypeControl] char(1) DEFAULT (' '),
    [MARCBibEncodingLevel] char(1) DEFAULT (' '),
    [MARCDescCatalogingForm] char(1) DEFAULT ('a'),
    [MARCLinkedRecordReq] char(1) DEFAULT (' '),
    [MARCPubDateOne] nchar(4),
    [MARCPubDateTwo] nchar(4),
    [MARCTargetAudience] char(1),
    [MARCLanguage] nchar(3) DEFAULT (N'eng'),
    [MARCPubPlace] nchar(3),
    [PublicationYear] smallint,
    [MARCCreationDate] nchar(6),
    [MARCModificationDate] nchar(16),
    [MARCLCCN] nvarchar(40),
    [MARCMedium] nvarchar(100),
    [MARCPublicationStatus] char(1) DEFAULT ('b'),
    [ILLFlag] bit DEFAULT (0),
    [MARCCharCodingScheme] char(1) DEFAULT (' '),
    [SortAuthor] nvarchar(255),
    [LiteraryForm] char(1),
    [RecordStatusDate] datetime DEFAULT (getdate()),
    [ModifiedByAuthorityJob] bit DEFAULT (0),
    [PrimaryMARCTOMID] tinyint,
    [FirstAvailableDate] datetime,
    [CreationDate] datetime DEFAULT (getdate()),
    [ModificationDate] datetime DEFAULT (getdate()),
    [LifetimeCircCount] int DEFAULT ((0)),
    [LifetimeInHouseUseCount] int DEFAULT ((0)),
    [SortTitle] nvarchar(255),
    [Popularity] int DEFAULT ((0)),
    [ImportedFileName] nvarchar(255),
    [BrowseTitleNonFilingCount] tinyint DEFAULT ((0)),
    [ImportedControlNumber] nvarchar(50),
    [ImportedRecordSource] nvarchar(50),
    [HasElectronicURL] bit DEFAULT ((0)),
    [DoNotOverlay] bit DEFAULT ((0)),
    [HostBibliographicRecordID] int,
    [HasConstituents] bit,
    [BoundWithCreatorID] int,
    [BoundWithCreationDate] datetime,
    [DisplayInPACLastChanged] datetime DEFAULT (getdate()),
    CONSTRAINT [fk_BibliographicRecords_CreatorID] FOREIGN KEY ([CreatorID]) REFERENCES [Polaris].[PolarisUsers]([PolarisUserID]),
    CONSTRAINT [fk_BibliographicRecords_PolarisUsers_BoundWithCreatorID] FOREIGN KEY ([BoundWithCreatorID]) REFERENCES [Polaris].[PolarisUsers]([PolarisUserID]),
    CONSTRAINT [fk_BibliographicRecords_HostBibliographicRecordID] FOREIGN KEY ([HostBibliographicRecordID]) REFERENCES [Polaris].[BibliographicRecords]([BibliographicRecordID]),
    CONSTRAINT [fk_BibliographicRecords_ModifierID] FOREIGN KEY ([ModifierID]) REFERENCES [Polaris].[PolarisUsers]([PolarisUserID]),
    CONSTRAINT [fk_BibliographicRecords_RecordStatusID] FOREIGN KEY ([RecordStatusID]) REFERENCES [Polaris].[RecordStatuses]([RecordStatusID]),
    CONSTRAINT [fk_BibliographicRecords_PrimaryMARCTOMID] FOREIGN KEY ([PrimaryMARCTOMID]) REFERENCES [Polaris].[MARCTypeOfMaterial]([MARCTypeOfMaterialID]),
    CONSTRAINT [fk_BibliographicRecords_RecordOwnerID] FOREIGN KEY ([RecordOwnerID]) REFERENCES [Polaris].[Organizations]([OrganizationID]),
    PRIMARY KEY ([BibliographicRecordID])
);