CREATE TABLE [Polaris].[SysHoldRequests] (
    [SysHoldRequestID] int IDENTITY,
    [Sequence] int DEFAULT (0),
    [PatronID] int,
    [PickupBranchID] int,
    [SysHoldStatusID] int DEFAULT (1),
    [RTFCyclesPrimary] int DEFAULT (0),
    [CreationDate] datetime DEFAULT (getdate()),
    [ActivationDate] datetime DEFAULT (getdate()),
    [ExpirationDate] datetime,
    [LastStatusTransitionDate] datetime DEFAULT (getdate()),
    [LCCN] nvarchar(40),
    [PublicationYear] smallint,
    [ISBN] nvarchar(50),
    [ISSN] nvarchar(50),
    [ItemBarcode] nvarchar(20),
    [BibliographicRecordID] int,
    [TrappingItemRecordID] int,
    [StaffDisplayNotes] nvarchar(255),
    [NonPublicNotes] nvarchar(255),
    [PatronNotes] nvarchar(255),
    [MessageID] uniqueidentifier,
    [HoldTillDate] datetime,
    [Origin] smallint,
    [Series] nvarchar(255),
    [Pages] nvarchar(255),
    [CreatorID] int,
    [ModifierID] int,
    [ModificationDate] datetime,
    [Publisher] nvarchar(40),
    [Edition] nvarchar(10),
    [VolumeNumber] nvarchar(60),
    [HoldNotificationDate] datetime,
    [DeliveryOptionID] int,
    [Suspended] bit DEFAULT (0),
    [UnlockedRequest] bit DEFAULT (0),
    [RTFCyclesSecondary] int DEFAULT (0),
    [PrimarySecondaryFlag] tinyint DEFAULT (1),
    [PrimaryRandomStartSequence] int DEFAULT (0),
    [SecondaryRandomStartSequence] int DEFAULT (0),
    [PrimaryMARCTOMID] tinyint,
    [ISBNNormalized] nvarchar(50),
    [ISSNNormalized] nvarchar(50),
    [Designation] nvarchar(780),
    [ItemLevelHold] bit DEFAULT ((0)),
    [ItemLevelHoldItemRecordID] int,
    [BorrowByMailRequest] bit DEFAULT ((0)),
    [PACDisplayNotes] nvarchar(255),
    [TrackingInfo] nvarchar(100),
    [HoldNotification2ndDate] datetime,
    [ConstituentBibRecordID] int,
    [PrimaryRTFBeginDate] datetime,
    [PrimaryRTFEndDate] datetime,
    [SecondaryRTFBeginDate] datetime,
    [SecondaryRTFEndDate] datetime,
    [NotSuppliedReasonCodeID] int,
    [NewPickupBranchID] int,
    [HoldPickupAreaID] int,
    [NewHoldPickupAreaID] int,
    [FeeInserted] bit DEFAULT ((0)),
    CONSTRAINT [fk_SysHoldRequests_TrappingItemRecordID] FOREIGN KEY ([TrappingItemRecordID]) REFERENCES [Polaris].[CircItemRecords]([ItemRecordID]),
    CONSTRAINT [fk_SysHoldRequests_Patrons] FOREIGN KEY ([PatronID]) REFERENCES [Polaris].[Patrons]([PatronID]),
    CONSTRAINT [fk_SysHoldRequests_ILL$Messages] FOREIGN KEY ([MessageID]) REFERENCES [Polaris].[ILL$Messages]([MessageID]),
    CONSTRAINT [fk_SysHoldRequests_Organizations] FOREIGN KEY ([PickupBranchID]) REFERENCES [Polaris].[Organizations]([OrganizationID]),
    CONSTRAINT [FK__SysHoldRe__NewHo__4BD54620] FOREIGN KEY ([NewHoldPickupAreaID]) REFERENCES [Polaris].[HoldPickupAreas]([HoldPickupAreaID]),
    CONSTRAINT [fk_SysHoldRequests_DeliveryOptionID] FOREIGN KEY ([DeliveryOptionID]) REFERENCES [Polaris].[SA_DeliveryOptions]([DeliveryOptionID]),
    CONSTRAINT [fk_SysHoldRequests_ConstituentBibRecordID] FOREIGN KEY ([ConstituentBibRecordID]) REFERENCES [Polaris].[BibliographicRecords]([BibliographicRecordID]),
    CONSTRAINT [fk_SysHoldRequests_New_Organizations] FOREIGN KEY ([NewPickupBranchID]) REFERENCES [Polaris].[Organizations]([OrganizationID]),
    CONSTRAINT [fk_SysHoldRequests_SysHoldStatuses] FOREIGN KEY ([SysHoldStatusID]) REFERENCES [Polaris].[SysHoldStatuses]([SysHoldStatusID]),
    CONSTRAINT [fk_SysHoldRequests_ItemLevelHoldItemRecordID] FOREIGN KEY ([ItemLevelHoldItemRecordID]) REFERENCES [Polaris].[CircItemRecords]([ItemRecordID]),
    CONSTRAINT [fk_SysHoldRequests_BibliographicRecords] FOREIGN KEY ([BibliographicRecordID]) REFERENCES [Polaris].[BibliographicRecords]([BibliographicRecordID]),
    CONSTRAINT [fk_SysHoldRequests_PrimaryMARCTOMID] FOREIGN KEY ([PrimaryMARCTOMID]) REFERENCES [Polaris].[MARCTypeOfMaterial]([MARCTypeOfMaterialID]),
    CONSTRAINT [FK__SysHoldRe__HoldP__3AAABA1E] FOREIGN KEY ([HoldPickupAreaID]) REFERENCES [Polaris].[HoldPickupAreas]([HoldPickupAreaID]),
    CONSTRAINT [fk_SysHoldRequests_SysHoldReasonCodes] FOREIGN KEY ([NotSuppliedReasonCodeID]) REFERENCES [Polaris].[SysHoldReasonCodes]([SysHoldReasonCodeID]),
    PRIMARY KEY ([SysHoldRequestID])